name: se7ety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
  
  fonts:
    - family: cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700

